/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nitro.custodian

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
    val grid = Grid(9)
}

fun main() {
    println(App().greeting)


    println(App().grid)
}
